import type { HeaderProps, FooterProps } from "@/types";
import "./globals.css";
import { cn } from "@/lib/utils";

import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";

import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { notFound } from "next/navigation";

const fontSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontHeading = Nunito({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function loader() {
  // TODO: you can fetch data from strapi here
  return {
    data: {
      topNav: mockHeader,
      footer: mockFooter,
    },
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await loader();
  if (!data) return notFound(); 
  const { topNav, footer } = data.data;

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-sans antialiased",
          fontSans.variable,
          fontHeading.variable
        )}
      >
        <Header data={topNav.data}/>
        {children}
        <Footer data={footer.data}/>
      </body>
    </html>
  );
}



const mockHeader: HeaderProps = {
  data: {
    logoText: "Strapi + Next.js",
    navItems: [
      {
        href: "/",
        text: "Home",
        isExternal: false,
        isPrimary: true,
      },
      {
        href: "/articles",
        text: "Blog",
        isExternal: false,
        isPrimary: false,
      },
    ],
    cta: {
      href: "https://strapi.io",
      text: "Try Strapi",
      isExternal: true,
      isPrimary: true,
    },
  },
};

const mockFooter: FooterProps = {
  data: {
    text: "Built with Strapi and Next.js",
    socialLinks: [
      {
        href: "https://youtube.com",
        text: "youtube",
        isExternal: true,
        isPrimary: false,
      },
      {
        href: "https://twitter.com",
        text: "twitter",
        isExternal: true,
        isPrimary: false,
      },
      {
        href: "https://github.com",
        text: "github",
        isExternal: true,
        isPrimary: false,
      },
    ],
  },
};
